BOOTSTRAP_SERVER='10.1.8.8:9092'
TOPIC_KAFKA='topic1'
GROUP_NAMES=['sensors']
ADAFRUIT_IO_USERNAME = "quangbinh"
ADAFRUIT_IO_KEY = "aio_grNV97RinHfoAC6LXFOOACyoU7PI"
SPARK_MASTER="spark://10.1.8.7:7077"
FEED_ID="soil"
LIGHT='light'
MOTOR='motor'
SOIL='soil'
TEMPERATURE='temperature'
HUMIDITY='humidity'
DATETIME_FORMAT="%H:%M:%S %d-%m-%Y"
FEEDS=['light','motor','soil','temperature','humidity']
